name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main
    types:
      - opened
      - synchronize
      - reopened
      - unlocked

jobs:
  test-parsing:
    concurrency:
      group: ci-${{ github.event.pull_request.number }}
      cancel-in-progress: true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v3

      - name: Setup tools
        run: |
          set -x
          node -v
          npm -v
          gcc -v
          npm install
          ./node_modules/.bin/tree-sitter --version

      - name: Generate the parser
        run: npm run generate

      - name: Check if generated files are up-to-date
        run: |
          if output="$(git diff-index HEAD)"; then
            files_changed_msg="$output"
          else
            fail_code=$?
          fi

          if [ "${fail_code:-}" ]; then
            exit $fail_code
          elif [ "${files_changed_msg:-}" ]; then
            >&2 echo \
              "Detected changes after generating parser files:" \
              $'\n'"$files_changed_msg"$'\n' \
              $'\n'"Please run \`npm run generate\` locally and push the changes"
            exit 1
          fi

      - name: Run the parsing tests
        run: npm run test-parsing
